#define APP_NAME "app"
#define CROSSPLATFORM_APP_FOLDER "./crossplatform_app"

#define SDL_IMPLEMENTATION

#define NK_IMPLEMENTATION
    // #define NK_SDL_GL3_IMPLEMENTATION
    #define NK_SDL_RENDERER_IMPLEMENTATION

#define INCLUDE_GAME_ENGINE_API
    // #define USE_GAME_OBJECT_COMPONENTS

#define INCLUDE_PHYSICS_API